ANNOUNCEMENT_PUBLISHED = 'ANNOUNCEMENT_PUBLISHED'
HOMEWORK_ASSIGNED = 'HOMEWORK_ASSIGNED'
STUDY_MATERIAL_UPLOADED = 'STUDY_MATERIAL_UPLOADED'
ATTENDANCE_ABSENT = 'ATTENDANCE_ABSENT'
PARENT_QUERY_RECEIVED = 'PARENT_QUERY_RECEIVED'
QUERY_REPLY_RECEIVED = 'QUERY_REPLY_RECEIVED'
CALENDAR_EVENT_CREATED = 'CALENDAR_EVENT_CREATED'
BULK_UPLOAD_COMPLETE = 'BULK_UPLOAD_COMPLETE'

NOTIFICATION_TYPE_CHOICES = [
    (ANNOUNCEMENT_PUBLISHED, 'Announcement Published'),
    (HOMEWORK_ASSIGNED, 'Homework Assigned'),
    (STUDY_MATERIAL_UPLOADED, 'Study Material Uploaded'),
    (ATTENDANCE_ABSENT, 'Attendance Absent'),
    (PARENT_QUERY_RECEIVED, 'Parent Query Received'),
    (QUERY_REPLY_RECEIVED, 'Query Reply Received'),
    (CALENDAR_EVENT_CREATED, 'Calendar Event Created'),
    (BULK_UPLOAD_COMPLETE, 'Bulk Upload Complete'),
]
