# Generated by Django 5.2.14 on 2026-05-08 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('parent', '0001_initial'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absentnotificationlog',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.parentprofile'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcementattachment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.announcement'),
        ),
        migrations.AddField(
            model_name='announcementtarget',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.academicclass'),
        ),
        migrations.AddField(
            model_name='announcementtarget',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.announcement'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='taken_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.teacherprofile'),
        ),
        migrations.AddField(
            model_name='homework',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.teacherprofile'),
        ),
        migrations.AddField(
            model_name='parentquery',
            name='assigned_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.teacherprofile'),
        ),
        migrations.AddField(
            model_name='parentquery',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.parentprofile'),
        ),
        migrations.AddField(
            model_name='parentquery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile'),
        ),
        migrations.AddField(
            model_name='parentqueryreply',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parentquery'),
        ),
        migrations.AddField(
            model_name='parentqueryreply',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentquery',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='homework',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='academicclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='academiccalendarevent',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='section',
            name='academic_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicclass'),
        ),
        migrations.AddField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacherprofile'),
        ),
        migrations.AddField(
            model_name='section',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='parentquery',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section'),
        ),
        migrations.AddField(
            model_name='homework',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section'),
        ),
        migrations.AddField(
            model_name='announcementtarget',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.section'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attendancesession'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile'),
        ),
        migrations.AddField(
            model_name='absentnotificationlog',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentattendance'),
        ),
        migrations.AddField(
            model_name='studentbulkuploadbatch',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='studentbulkuploadbatch',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentbulkuploadrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentbulkuploadbatch'),
        ),
        migrations.AddField(
            model_name='studentbulkuploadrow',
            name='created_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent.parentprofile'),
        ),
        migrations.AddField(
            model_name='studentbulkuploadrow',
            name='created_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentprofile'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.teacherprofile'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subject'),
        ),
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subject'),
        ),
        migrations.AddConstraint(
            model_name='academicclass',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_class_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('academic_class', 'name'), name='unique_section_name_per_class'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('section', 'date', 'slot'), name='unique_attendance_session_per_section_date_slot'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_student_attendance_per_session'),
        ),
        migrations.AddConstraint(
            model_name='studentbulkuploadrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_student_upload_row_number_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_subject_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('school', 'code'), name='unique_subject_code_per_school_when_set'),
        ),
    ]
