# Generated by Django 5.2.14 on 2026-05-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='parent_query_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
