# Generated by Codex on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workflow_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(
                condition=models.Q(('phone_number__isnull', False)) & ~models.Q(('phone_number', '')),
                fields=('phone_number',),
                name='unique_user_phone_number_when_set',
            ),
        ),
    ]
