# Generated by Django 5.2.14 on 2026-05-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_section_parent_query_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='announcementattachment',
            name='file',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.URLField(max_length=500),
        ),
    ]
