# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_profile_pic_urlfield_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('ADMIN', 'Admin'),
                    ('PRINCIPAL', 'Principal'),
                    ('TEACHER', 'Teacher'),
                    ('STUDENT', 'Student'),
                    ('PARENT', 'Parent'),
                ],
                max_length=20,
            ),
        ),
    ]
