# Generated by Django 5.2.13 on 2026-05-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teacherbulkuploadbatch_teacherbulkuploadrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
