# Generated by Codex on 2026-05-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_uploaded_by_profile_user(apps, schema_editor):
    StudentBulkUploadBatch = apps.get_model('core', 'StudentBulkUploadBatch')
    PrincipalProfile = apps.get_model('principal', 'PrincipalProfile')
    db_alias = schema_editor.connection.alias

    batches = StudentBulkUploadBatch.objects.using(db_alias).exclude(uploaded_by_id__isnull=True)
    for batch in batches:
        profile = PrincipalProfile.objects.using(db_alias).filter(pk=batch.uploaded_by_id).first()
        if profile is None:
            continue
        batch.uploaded_by_user_id = profile.user_id
        batch.save(update_fields=['uploaded_by_user'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_add_admin_role'),
        ('principal', '0002_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbulkuploadbatch',
            name='uploaded_by_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(copy_uploaded_by_profile_user, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='studentbulkuploadbatch',
            name='uploaded_by',
        ),
        migrations.RenameField(
            model_name='studentbulkuploadbatch',
            old_name='uploaded_by_user',
            new_name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='studentbulkuploadbatch',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
