# Generated by Django 5.2.14 on 2026-05-07 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_user_profile_pic_urlfield_files'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_date', models.DateField()),
                ('analytics_status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_exams', to='core.school')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-exam_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_ref_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=20)),
                ('section_name', models.CharField(max_length=10)),
                ('academic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_students', to='core.academicclass')),
                ('linked_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_student', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_students', to='core.school')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_students', to='core.section')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(choices=[('MATHS', 'Maths'), ('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry')], max_length=20)),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('max_marks', models.PositiveSmallIntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='analytics.analyticsexam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_marks', models.IntegerField()),
                ('exam_rank', models.PositiveIntegerField()),
                ('correct', models.PositiveSmallIntegerField()),
                ('wrong', models.PositiveSmallIntegerField()),
                ('unattempted', models.PositiveSmallIntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analytics.analyticsexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analytics.analyticsstudent')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analytics.examsubject')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_no', models.PositiveSmallIntegerField()),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('skip_count', models.PositiveIntegerField(default=0)),
                ('difficulty_index', models.FloatField(default=0.0)),
                ('difficulty_tag', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='HARD', max_length=6)),
                ('discrimination_index', models.FloatField(default=0.0)),
                ('has_key_error', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_analytics', to='analytics.analyticsexam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_analytics', to='analytics.examsubject')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('q_no', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('C', 'Correct'), ('W', 'Wrong'), ('U', 'Unattempted')], max_length=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='analytics.analyticsexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='analytics.analyticsstudent')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='analytics.examsubject')),
            ],
        ),
        migrations.CreateModel(
            name='SectionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_marks', models.FloatField(default=0.0)),
                ('median_marks', models.FloatField(default=0.0)),
                ('std_dev', models.FloatField(default=0.0)),
                ('at_risk_count', models.PositiveIntegerField(default=0)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_analytics', to='core.academicclass')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_analytics', to='analytics.analyticsexam')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_analytics', to='core.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_analytics', to='analytics.examsubject')),
                ('top_scorer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topped_sections', to='analytics.analyticsstudent')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_score', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_label', models.CharField(choices=[('SAFE', 'Safe'), ('WATCH', 'Watch'), ('ALERT', 'Alert')], default='SAFE', max_length=5)),
                ('performance_label', models.CharField(choices=[('EXCEPTIONAL', 'Exceptional'), ('ABOVE_AVERAGE', 'Above Average'), ('AVERAGE', 'Average'), ('BELOW_AVERAGE', 'Below Average'), ('NEEDS_ATTENTION', 'Needs Attention')], default='AVERAGE', max_length=20)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_risks', to='analytics.analyticsexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='analytics.analyticsstudent')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_risks', to='analytics.examsubject')),
            ],
        ),
        migrations.AddConstraint(
            model_name='analyticsstudent',
            constraint=models.UniqueConstraint(fields=('student_ref_id', 'school'), name='unique_student_ref_per_school'),
        ),
        migrations.AddConstraint(
            model_name='examsubject',
            constraint=models.UniqueConstraint(fields=('exam', 'subject_name'), name='unique_subject_per_exam'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('exam', 'student', 'subject'), name='unique_result_per_student_subject_exam'),
        ),
        migrations.AddConstraint(
            model_name='questionanalytics',
            constraint=models.UniqueConstraint(fields=('exam', 'subject', 'q_no'), name='unique_question_analytics'),
        ),
        migrations.AddIndex(
            model_name='questionresult',
            index=models.Index(fields=['exam', 'subject', 'q_no'], name='analytics_q_exam_id_d03864_idx'),
        ),
        migrations.AddIndex(
            model_name='questionresult',
            index=models.Index(fields=['exam', 'student'], name='analytics_q_exam_id_354d58_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionresult',
            constraint=models.UniqueConstraint(fields=('exam', 'student', 'subject', 'q_no'), name='unique_question_result_per_student'),
        ),
        migrations.AddConstraint(
            model_name='sectionanalytics',
            constraint=models.UniqueConstraint(fields=('exam', 'section', 'subject'), name='unique_section_analytics'),
        ),
        migrations.AddConstraint(
            model_name='studentrisk',
            constraint=models.UniqueConstraint(fields=('exam', 'student', 'subject'), name='unique_student_risk'),
        ),
    ]
