# Generated by Django 5.2.14 on 2026-05-08 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_date', models.DateField()),
                ('analytics_status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
            ],
            options={
                'ordering': ['-exam_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_ref_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=20)),
                ('section_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_marks', models.IntegerField()),
                ('exam_rank', models.PositiveIntegerField()),
                ('correct', models.PositiveSmallIntegerField()),
                ('wrong', models.PositiveSmallIntegerField()),
                ('unattempted', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(choices=[('MATHS', 'Maths'), ('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry')], max_length=20)),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('max_marks', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_no', models.PositiveSmallIntegerField()),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('skip_count', models.PositiveIntegerField(default=0)),
                ('difficulty_index', models.FloatField(default=0.0)),
                ('difficulty_tag', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='HARD', max_length=6)),
                ('discrimination_index', models.FloatField(default=0.0)),
                ('has_key_error', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('q_no', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('C', 'Correct'), ('W', 'Wrong'), ('U', 'Unattempted')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SectionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_marks', models.FloatField(default=0.0)),
                ('median_marks', models.FloatField(default=0.0)),
                ('std_dev', models.FloatField(default=0.0)),
                ('at_risk_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_score', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_label', models.CharField(choices=[('SAFE', 'Safe'), ('WATCH', 'Watch'), ('ALERT', 'Alert')], default='SAFE', max_length=5)),
                ('performance_label', models.CharField(choices=[('EXCEPTIONAL', 'Exceptional'), ('ABOVE_AVERAGE', 'Above Average'), ('AVERAGE', 'Average'), ('BELOW_AVERAGE', 'Below Average'), ('NEEDS_ATTENTION', 'Needs Attention')], default='AVERAGE', max_length=20)),
            ],
        ),
    ]
