# Generated by Django 5.2.14 on 2026-05-08 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsexam',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_exams', to='core.school'),
        ),
        migrations.AddField(
            model_name='analyticsexam',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticsstudent',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_students', to='core.academicclass'),
        ),
        migrations.AddField(
            model_name='analyticsstudent',
            name='linked_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticsstudent',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_students', to='core.school'),
        ),
        migrations.AddField(
            model_name='analyticsstudent',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_students', to='core.section'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analytics.analyticsexam'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analytics.analyticsstudent'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='core_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_subjects', to='core.subject'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='analytics.analyticsexam'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analytics.examsubject'),
        ),
        migrations.AddField(
            model_name='questionanalytics',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_analytics', to='analytics.analyticsexam'),
        ),
        migrations.AddField(
            model_name='questionanalytics',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_analytics', to='analytics.examsubject'),
        ),
        migrations.AddField(
            model_name='questionresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='analytics.analyticsexam'),
        ),
        migrations.AddField(
            model_name='questionresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='analytics.analyticsstudent'),
        ),
        migrations.AddField(
            model_name='questionresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='analytics.examsubject'),
        ),
        migrations.AddField(
            model_name='sectionanalytics',
            name='academic_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_analytics', to='core.academicclass'),
        ),
        migrations.AddField(
            model_name='sectionanalytics',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_analytics', to='analytics.analyticsexam'),
        ),
        migrations.AddField(
            model_name='sectionanalytics',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_analytics', to='core.section'),
        ),
        migrations.AddField(
            model_name='sectionanalytics',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_analytics', to='analytics.examsubject'),
        ),
        migrations.AddField(
            model_name='sectionanalytics',
            name='top_scorer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topped_sections', to='analytics.analyticsstudent'),
        ),
        migrations.AddField(
            model_name='studentrisk',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_risks', to='analytics.analyticsexam'),
        ),
        migrations.AddField(
            model_name='studentrisk',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='analytics.analyticsstudent'),
        ),
        migrations.AddField(
            model_name='studentrisk',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_risks', to='analytics.examsubject'),
        ),
        migrations.AddConstraint(
            model_name='analyticsstudent',
            constraint=models.UniqueConstraint(fields=('student_ref_id', 'school'), name='unique_student_ref_per_school'),
        ),
        migrations.AddConstraint(
            model_name='examsubject',
            constraint=models.UniqueConstraint(fields=('exam', 'subject_name'), name='unique_subject_per_exam'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('exam', 'student', 'subject'), name='unique_result_per_student_subject_exam'),
        ),
        migrations.AddConstraint(
            model_name='questionanalytics',
            constraint=models.UniqueConstraint(fields=('exam', 'subject', 'q_no'), name='unique_question_analytics'),
        ),
        migrations.AddIndex(
            model_name='questionresult',
            index=models.Index(fields=['exam', 'subject', 'q_no'], name='analytics_q_exam_id_d03864_idx'),
        ),
        migrations.AddIndex(
            model_name='questionresult',
            index=models.Index(fields=['exam', 'student'], name='analytics_q_exam_id_354d58_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionresult',
            constraint=models.UniqueConstraint(fields=('exam', 'student', 'subject', 'q_no'), name='unique_question_result_per_student'),
        ),
        migrations.AddConstraint(
            model_name='sectionanalytics',
            constraint=models.UniqueConstraint(fields=('exam', 'section', 'subject'), name='unique_section_analytics'),
        ),
        migrations.AddConstraint(
            model_name='studentrisk',
            constraint=models.UniqueConstraint(fields=('exam', 'student', 'subject'), name='unique_student_risk'),
        ),
    ]
