from .profile import ParentProfilePresenter
from .attendance import ParentAttendancePresenter
from .announcements import ParentAnnouncementsPresenter
from .study_materials import ParentStudyMaterialsPresenter
from .homework import ParentHomeworkPresenter
from .calendar import ParentCalendarPresenter
from .exams import ParentExamPresenter
from .queries import ParentQueriesPresenter
from .profile_pic import ProfilePicPresenter
