# Generated by Django 5.2.14 on 2026-05-08 08:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(blank=True, max_length=30)),
                ('admission_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.academicclass')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('admission_number', ''), _negated=True), fields=('school', 'admission_number'), name='unique_student_admission_number_per_school_when_set'), models.UniqueConstraint(condition=models.Q(('roll_number', ''), _negated=True), fields=('section', 'roll_number'), name='unique_student_roll_number_per_section_when_set')],
            },
        ),
    ]
