# Generated by Django 5.2.14 on 2026-05-07 05:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notif_type', models.CharField(choices=[('ANNOUNCEMENT_PUBLISHED', 'Announcement Published'), ('HOMEWORK_ASSIGNED', 'Homework Assigned'), ('STUDY_MATERIAL_UPLOADED', 'Study Material Uploaded'), ('ATTENDANCE_ABSENT', 'Attendance Absent'), ('PARENT_QUERY_RECEIVED', 'Parent Query Received'), ('QUERY_REPLY_RECEIVED', 'Query Reply Received'), ('CALENDAR_EVENT_CREATED', 'Calendar Event Created'), ('BULK_UPLOAD_COMPLETE', 'Bulk Upload Complete')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notif_recipient_read_idx'), models.Index(fields=['recipient', 'created_at'], name='notif_recipient_created_idx')],
            },
        ),
    ]
